using System;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.Threading;
using Spectre.Console;
using Spectre.Console.Cli;

namespace CXEX.CLI.Commands;

public class EmbedCommand : Command<EmbedCommand.Settings>
{
    public class Settings : CommandSettings
    {
        [CommandArgument(0, "<INPUT_FILE>")]
        [Description("The binary file to embed (e.g., hello.xcex)")]
        public string InputPath { get; set; } = string.Empty;

        [CommandArgument(1, "<OUTPUT_HEADER>")]
        [Description("The C header file to generate (e.g., app_image.h)")]
        public string OutputPath { get; set; } = string.Empty;

        [CommandArgument(2, "<VAR_NAME>")]
        [Description("The C variable name for the array (e.g., hello_xcex)")]
        public string VarName { get; set; } = string.Empty;
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        if (!File.Exists(settings.InputPath))
        {
            AnsiConsole.MarkupLine($"[red]Error:[/] Input file '{settings.InputPath}' not found.");
            return 1;
        }

        byte[] data = File.ReadAllBytes(settings.InputPath);
        var sb = new StringBuilder();

        sb.AppendLine($"/* GENERATED BY CXK CLI */");
        sb.AppendLine($"#ifndef {settings.VarName.ToUpper()}_H");
        sb.AppendLine($"#define {settings.VarName.ToUpper()}_H");
        sb.AppendLine($"static const unsigned char {settings.VarName}[] = {{");

        for (int i = 0; i < data.Length; i++)
        {
            if (i % 12 == 0) sb.Append("    ");
            sb.Append($"0x{data[i]:x2},");
            if ((i + 1) % 12 == 0 || i == data.Length - 1) sb.AppendLine();
        }

        sb.AppendLine($"}};");
        sb.AppendLine($"static const unsigned int {settings.VarName}_len = {data.Length};");
        sb.AppendLine($"#endif");

        File.WriteAllText(settings.OutputPath, sb.ToString());
        AnsiConsole.MarkupLine($"[green]SUCCESS:[/] Generated C header [cyan]{settings.OutputPath}[/] ({data.Length} bytes)");
        return 0;
    }
}