using System;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.Threading;
using Spectre.Console;
using Spectre.Console.Cli;

namespace CXEX.CLI.Commands;

/// <summary>
/// Embeds a binary as a C byte array. Replaces embedkey.py / make_app_image.py.
///
/// Two linkage models, because the kernel uses both:
///
///   default (--static, the norm): a self-contained guarded header with a
///     `static const` array. The consumer just #includes it. This is how the
///     executive pulls in app_image.h (hello_xcex[]).
///
///   --extern: a split .c + .h pair. The .c DEFINES non-static symbols; the .h
///     DECLARES them `extern`. This is how the kernel links its root of trust:
///     trusted_key.c is its own translation unit, and cxex_verify.c reaches the
///     symbol through trusted_key.h. A `static` array cannot cross that boundary
///     -- it would link-fail with "undefined reference to cxos_trusted_key".
/// </summary>
public class EmbedCommand : Command<EmbedCommand.Settings>
{
    public class Settings : CommandSettings
    {
        [CommandArgument(0, "<INPUT_FILE>")]
        [Description("The binary file to embed (e.g. hello.xcex, kernel.xkpk)")]
        public string InputPath { get; set; } = string.Empty;

        [CommandArgument(1, "<OUTPUT>")]
        [Description("Output C file. --extern writes this .c AND a sibling .h; default writes a single header.")]
        public string OutputPath { get; set; } = string.Empty;

        [CommandArgument(2, "<VAR_NAME>")]
        [Description("C variable name for the array (e.g. hello_xcex, cxos_trusted_key)")]
        public string VarName { get; set; } = string.Empty;

        [CommandOption("--extern")]
        [Description("Emit a linkable .c (non-static) plus a matching extern .h. Use for the kernel's trusted_key.")]
        public bool Extern { get; set; }
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        if (!File.Exists(settings.InputPath))
        {
            AnsiConsole.MarkupLine($"[red]Error:[/] Input file '{settings.InputPath}' not found.");
            return 1;
        }

        byte[] data = File.ReadAllBytes(settings.InputPath);

        if (settings.Extern)
            return EmitExtern(settings, data);
        return EmitStaticHeader(settings, data);
    }

    /// <summary>Default: one self-contained guarded header, `static const`.</summary>
    private static int EmitStaticHeader(Settings s, byte[] data)
    {
        string guard = GuardFor(s.OutputPath, s.VarName);
        var sb = new StringBuilder();
        sb.AppendLine("/* GENERATED BY CXK CLI */");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine($"static const unsigned char {s.VarName}[] = {{");
        AppendBytes(sb, data);
        sb.AppendLine("};");
        sb.AppendLine($"static const unsigned int {s.VarName}_len = {data.Length};");
        sb.AppendLine("#endif");

        File.WriteAllText(s.OutputPath, sb.ToString());
        AnsiConsole.MarkupLine($"[green]SUCCESS:[/] Generated header [cyan]{s.OutputPath}[/] ({data.Length} bytes, static)");
        return 0;
    }

    /// <summary>--extern: a linkable .c (non-static) + a matching extern .h.</summary>
    private static int EmitExtern(Settings s, byte[] data)
    {
        // Normalize paths: the .c is what the user named; the .h sits beside it.
        string cPath = Path.ChangeExtension(s.OutputPath, ".c");
        string hPath = Path.ChangeExtension(s.OutputPath, ".h");
        string hName = Path.GetFileName(hPath);
        string guard = GuardFor(hPath, s.VarName);

        var h = new StringBuilder();
        h.AppendLine("/* GENERATED BY CXK CLI - DO NOT EDIT */");
        h.AppendLine($"#ifndef {guard}");
        h.AppendLine($"#define {guard}");
        h.AppendLine();
        h.AppendLine($"extern const unsigned char {s.VarName}[];");
        h.AppendLine($"extern const unsigned int  {s.VarName}_len;");
        h.AppendLine();
        h.AppendLine("#endif");
        File.WriteAllText(hPath, h.ToString());

        var c = new StringBuilder();
        c.AppendLine("/* GENERATED BY CXK CLI - DO NOT EDIT */");
        c.AppendLine($"#include \"{hName}\"");
        c.AppendLine();
        c.AppendLine($"const unsigned char {s.VarName}[] = {{");
        AppendBytes(c, data);
        c.AppendLine("};");
        c.AppendLine($"const unsigned int {s.VarName}_len = {data.Length};");
        File.WriteAllText(cPath, c.ToString());

        AnsiConsole.MarkupLine($"[green]SUCCESS:[/] Generated [cyan]{cPath}[/] + [cyan]{hPath}[/] ({data.Length} bytes, extern)");
        return 0;
    }

    private static void AppendBytes(StringBuilder sb, byte[] data)
    {
        for (int i = 0; i < data.Length; i++)
        {
            if (i % 12 == 0) sb.Append("    ");
            sb.Append($"0x{data[i]:x2},");
            if ((i + 1) % 12 == 0 || i == data.Length - 1) sb.AppendLine();
        }
    }

    // A C-identifier-safe include guard. Prefer the file name so two arrays in
    // different files don't collide on the same guard.
    private static string GuardFor(string path, string varName)
    {
        string basis = Path.GetFileName(path);
        if (string.IsNullOrEmpty(basis)) basis = varName;
        var sb = new StringBuilder(basis.Length + 1);
        foreach (char ch in basis)
            sb.Append(char.IsLetterOrDigit(ch) ? char.ToUpperInvariant(ch) : '_');
        // guard can't start with a digit
        if (sb.Length > 0 && char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}
