#!/usr/bin/env python3
# /CXK/tools/CXEX_Compiler/embedkey.py
# Aurora Tejeda / CATX SYSTEMS LLC
#
# Bake a trusted .xkpk public key into the kernel as a C byte array, so the
# kernel's ROOT OF TRUST is compiled in. The key must not be read from disk at
# runtime - a key file sitting next to the images it signs is circular (whoever
# can replace an image can replace the key). The kernel itself is signed and
# loaded by the verified boot chain, so it is the right place to anchor trust.
#
# Run at build time, or whenever the signing key is rotated.
#
# Usage:  python embedkey.py <key.xkpk> <out_basename>
#   e.g.  python embedkey.py kernel.xkpk ../../kernel/lib/format/trusted_key
#         -> trusted_key.c + trusted_key.h
import sys, os

def main():
    if len(sys.argv) != 3:
        print("usage: python embedkey.py <key.xkpk> <out_basename>")
        raise SystemExit(2)
    src, base = sys.argv[1], sys.argv[2]
    data = open(src, "rb").read()
    if data[:4] != b"CXPK":
        raise SystemExit("error: %s is not a CXPK (.xkpk) public key" % src)
    name = os.path.basename(src)

    with open(base + ".h", "w") as h:
        h.write("/* GENERATED by embedkey.py from %s - DO NOT EDIT */\n" % name)
        h.write("/* The kernel's compiled-in root of trust: a CXPK public key. */\n")
        h.write("#ifndef TRUSTED_KEY_H\n#define TRUSTED_KEY_H\n\n")
        h.write("extern const unsigned char cxos_trusted_key[];\n")
        h.write("extern const unsigned int  cxos_trusted_key_len;\n\n")
        h.write("#endif\n")

    with open(base + ".c", "w") as c:
        c.write("/* GENERATED by embedkey.py from %s - DO NOT EDIT */\n" % name)
        c.write('#include "trusted_key.h"\n\n')
        c.write("const unsigned char cxos_trusted_key[] = {\n")
        for i in range(0, len(data), 12):
            row = ", ".join("0x%02x" % b for b in data[i:i+12])
            c.write("    " + row + ",\n")
        c.write("};\n")
        c.write("const unsigned int cxos_trusted_key_len = %d;\n" % len(data))

    print("wrote %s.h and %s.c (%d bytes embedded from %s)" % (base, base, len(data), name))

if __name__ == "__main__":
    main()