#!/usr/bin/env python3
# /CXK/tools/make_app_image.py
# Aurora Tejeda / CATX SYSTEMS LLC
# Rebuild the tiny hello .xcex and regenerate os/executive/app_image.h (the
# committed byte array the executive embeds and hands to spawn). Run after
# changing os/apps/hello/. Requires the cross gcc on PATH (or edit CC below).
import subprocess, sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CC   = os.environ.get("KCC", "i686-elf-gcc")
src  = os.path.join(ROOT, "os/apps/hello/hello.c")
ld   = os.path.join(ROOT, "os/apps/hello/hello.ld")
elf  = os.path.join(ROOT, "build/hello.elf")
xcex = os.path.join(ROOT, "build/hello.xcex")
hdr  = os.path.join(ROOT, "os/executive/app_image.h")
os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
subprocess.run([CC, "-ffreestanding","-fno-pic","-no-pie","-fno-stack-protector","-nostdlib",
                "-I", os.path.join(ROOT,"abi"), "-Wl,-T,"+ld, "-o", elf, src], check=True)
subprocess.run([sys.executable, os.path.join(ROOT,"tools/CXEX_Compiler/mkcxes.py"),
                elf, xcex, "--type","user"], check=True)
data = open(xcex,"rb").read()
out = ["/* /CXK/os/executive/app_image.h - GENERATED by tools/make_app_image.py */",
       "#ifndef APP_IMAGE_H","#define APP_IMAGE_H",
       "static const unsigned char hello_xcex[] = {"]
for i in range(0,len(data),12):
    out.append("    "+",".join("0x%02x"%b for b in data[i:i+12])+",")
out += ["};", "static const unsigned int hello_xcex_len = %d;"%len(data), "#endif"]
open(hdr,"w",newline="").write("\r\n".join(out)+"\r\n")
print("regenerated app_image.h (%d bytes)"%len(data))