// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Aurora Tejeda (trading as CATX Systems)
/* /kernel/lib/gfx/klogo.c */
/* Aurora Tejeda / CATX Systems */
/*
 * Vector CX logo renderer. The logo is stored (logo_vec.h, generated by
 * svg2cxlogo.py) as fixed-point flattened polygons in a CXLOGO_VIEW-unit box.
 * We rasterize it at an arbitrary pixel size with an even-odd scanline fill,
 * using only 32-bit integer math (no float, no 64-bit divide) so it's safe in
 * freestanding kernel code. Resolution-independent: scales clean from 320x200
 * up to 1080p.
 *
 * The #000000 background path is skipped (DROP_BG) so the logo is transparent -
 * it composites onto whatever the framebuffer already holds.
 */

#include "klogo.h"
#include "logo_vec.h"
#include "fb.h"

#define DROP_BG       1     /* skip the pure-black background path */
#define MAX_CROSS     64    /* max edge crossings per scanline (logo is simple) */

/* map a coordinate in FP view units to a pixel offset within a `size`-px box */
static inline int32_t view_to_px(int32_t v, uint32_t size) {
    /* v up to CXLOGO_VIEW*CXLOGO_FP (9600); size up to a few thousand.
       9600 * size stays well within 32 bits for any sane resolution. */
    return (v * (int32_t)size) / (CXLOGO_VIEW * CXLOGO_FP);
}

/* insertion sort a small int32 array ascending */
static void sort_i32(int32_t *a, int n) {
    for (int i = 1; i < n; i++) {
        int32_t key = a[i];
        int j = i - 1;
        while (j >= 0 && a[j] > key) { a[j + 1] = a[j]; j--; }
        a[j + 1] = key;
    }
}

void klogo_draw(uint32_t ox, uint32_t oy, uint32_t size) {
    if (!fb_active() || size == 0) return;

    const int32_t denom = CXLOGO_VIEW * CXLOGO_FP;   /* 9600 */

    for (uint32_t pi = 0; pi < CXLOGO_NPATHS; pi++) {
        const cxlogo_path_t *P = &cxlogo_paths[pi];
        if (DROP_BG && P->r == 0 && P->g == 0 && P->b == 0) continue;
        uint32_t color = fb_rgb(P->r, P->g, P->b);

        for (uint32_t py = 0; py < size; py++) {
            /* sample at the scanline center, expressed in FP view units:
               yv = ((py*2 + 1) * denom) / (2*size)  - all 32-bit */
            int32_t yv = (int32_t)(((py * 2u + 1u) * (uint32_t)denom) / (2u * size));

            int32_t xs[MAX_CROSS];
            int n = 0;

            /* gather edge crossings across every subpath of this path */
            for (uint32_t si = P->sub_start; si < P->sub_start + P->sub_count; si++) {
                const cxlogo_sub_t *S = &cxlogo_subs[si];
                uint32_t base = S->start, cnt = S->count;
                for (uint32_t k = 0; k < cnt; k++) {
                    const cxlogo_vert_t *a = &cxlogo_verts[base + k];
                    const cxlogo_vert_t *b = &cxlogo_verts[base + (k + 1) % cnt];
                    int32_t y0 = a->y, y1 = b->y;
                    if (y0 == y1) continue;                       /* horizontal: skip */
                    /* does scanline yv cross [y0,y1)? (half-open avoids double count) */
                    int crosses = (y0 <= yv && yv < y1) || (y1 <= yv && yv < y0);
                    if (!crosses) continue;
                    int32_t x0 = a->x, x1 = b->x;
                    /* xv = x0 + (x1-x0)*(yv-y0)/(y1-y0)   in FP view units */
                    int32_t xv = x0 + (int32_t)(((int32_t)(x1 - x0) * (yv - y0)) / (y1 - y0));
                    if (n < MAX_CROSS) xs[n++] = view_to_px(xv, size);
                }
            }
            if (n < 2) continue;
            sort_i32(xs, n);

            /* fill between crossing pairs (even-odd) */
            for (int k = 0; k + 1 < n; k += 2) {
                int32_t xa = xs[k], xb = xs[k + 1];
                if (xb < xa) { int32_t t = xa; xa = xb; xb = t; }
                if (xb < 0) continue;
                if (xa < 0) xa = 0;
                fb_fill_rect(ox + (uint32_t)xa, oy + py,
                             (uint32_t)(xb - xa + 1), 1, color);
            }
        }
    }
}

/* Draw the logo centered in the framebuffer at `size` px square, clamping so a
   logo larger than the screen top-left aligns instead of underflowing. Pass
   size 0 to auto-fit ~60% of the smaller screen dimension. */
void klogo_draw_centered(uint32_t size) {
    if (!fb_active()) return;
    uint32_t w = fb_width(), h = fb_height();

    if (size == 0) {
        uint32_t smaller = (w < h) ? w : h;
        size = (smaller * 3) / 5;          /* ~60% of the short edge */
        if (size == 0) return;
    }

    uint32_t ox = (w > size) ? (w - size) / 2 : 0;
    uint32_t oy = (h > size) ? (h - size) / 2 : 0;
    klogo_draw(ox, oy, size);
}