/* GENERATED by embedkey.py from kernel.xkpk - DO NOT EDIT */
/* The kernel's compiled-in root of trust: a CXPK public key. */
#ifndef TRUSTED_KEY_H
#define TRUSTED_KEY_H

extern const unsigned char cxos_trusted_key[];
extern const unsigned int  cxos_trusted_key_len;

#endif
