// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Aurora Tejeda (trading as CATX Systems)
/* GENERATED BY CXK CLI - DO NOT EDIT */
#ifndef TRUSTED_KEY_H
#define TRUSTED_KEY_H

extern const unsigned char cxos_trusted_key[];
extern const unsigned int  cxos_trusted_key_len;

#endif
